### ISSUE TITLE
issue raised 

### ISSUE THREAD

**Issue by happyjin** [ppriyank/Video-Action-Transformer-Network-Pytorch-#1]
Hi,
Thanks for your awesome project. I found a dependence issue when I try to run transformer_v3.py. Could you please tell me which dependence do I need? Thanks in advance!
```
from tools import BNClassifier, BottleSoftmax
ImportError: cannot import name 'BNClassifier' from 'tools' (unknown location)
```

**Comment by ppriyank** [comment]
Oh, I forgot to upload that file.
It's uploaded now, Do let me know if any of these transformer work really well.
