### ISSUE TITLE
One implementation problem in transformer_v3.py

### ISSUE THREAD

**Issue by VincentCheng24** [ppriyank/Video-Action-Transformer-Network-Pytorch-#3]
It seems that the function defined [here](https://github.com/ppriyank/Video-Action-Transformer-Network-Pytorch-/blob/master/transformer_v3.py#L138) needs to be modified as follows: 
```
    def forward(self, q, k, v, mask=None):
        bs = k.shape[0]
        k = k.view(bs, -1, self.head, self.d_k)
        q = F.relu(self.q_linear(q).view(bs, self.head, self.d_k))
        ...
```
Please help check this.
BTW, thanks for sharing this implementation.

**Comment by ppriyank** [comment]
Oh, yes, I have no idea how did I miss this. Very Very sorry about this. Yes, you are correct. **self.** needs to be added there
